# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 821a7531f48254f4569fae3e31abead35fb0a44fae337f157d0b2f02e9930f9f0ee99e71799fd6fb9dea4de6f361e93e6cb8d5ed74e389601063c1fb8b2b6e16

test:
  secret_key_base: 29c1843bd6ac146f0424714b160f10304cb3865955403284c8cff240c03648bf16b1a194ccc1c72b7a9ba780046dc3bb66242b345f1f975c4a5c91e39662da3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
